name: Deploy to Firebase

on:
  push:
    branches: [ develop, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Android Environment
        uses: ./.github/actions/setup-android
        with:
          firebase-json: ${{ secrets.FIREBASE_JSON }}
          bearer-token: ${{ secrets.BEARER_TOKEN }}

      - name: Clean Project
        run: ./gradlew clean

      - name: Generate APK
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/aflami-amsterdam.apk

      - name: Upload APK to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            app/build/outputs/apk/release/aflami-amsterdam.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups ${{ secrets.TESTER_GROUP }}