name: Deploy to Firebase

on:
  push:
    branches: [ develop, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.FIREBASE_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Create local.properties
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          echo "bearerToken=$BEARER_TOKEN" > local.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Build Project
        run: ./gradlew build

      - name: Generate APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            app/build/outputs/apk/debug/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups ${{ secrets.TESTER_GROUP }}